# Prepare
```{r}
library(tidyverse, warn.conflicts = F)
library(plotly)
library(ggplot2, warn.conflicts = F)
library(purrr) # for functional programming
df <- read.csv("data/netflix_titles.csv", na.strings = c("", "NA"))
```

# Get country information

```{r}
grouped <- df %>%
  filter(!is.na(country) & country != "") %>% # remove the NA country
  filter(!is.na(date_added)) %>% # remove the NA date_added
  mutate(year_added = year(parse_date(date_added, "%B %d, %Y"))) %>% # extract year_added
  mutate(country = strsplit(as.character(country), ",")) %>%
  mutate(country = lapply(country, trimws)) %>%
  unnest(country) %>%
  group_by(country, year_added, type) %>%
  summarise(cnt = n()) %>%
  filter(!is.na(country) & country != "")
```

# Grouping
```{r}
by_country_type <- grouped %>%
  group_by(country, type) %>%
  summarise(cnt = sum(cnt))
```
# Movie Distribution by country
```{r}
plot_ly(by_country_type %>% filter(type == "Movie"),
  type = "choropleth",
  locations = ~country,
  locationmode = "country names",
  z = ~cnt,
  color = ~cnt,
  colors = "OrRd",
  colorbar = list(title = "Counts"),
  text = ~ paste(country, "<br>Counts: ", cnt)
)
```
# TV Show Distribution by contry
```{r}
plot_ly(by_country_type %>% filter(type == "TV Show"),
  type = "choropleth",
  locations = ~country,
  locationmode = "country names",
  z = ~cnt,
  color = ~cnt,
  colors = "OrRd",
  colorbar = list(title = "Counts"),
  text = ~ paste(country, "<br>Counts: ", cnt)
)
```

# Accum TV shows & Movie
```{r}
country_accum <- grouped %>%
  group_by(country, year_added) %>%
  summarise(cnt = sum(cnt)) %>%
  group_by(country) %>%
  arrange(year_added) %>%
  mutate(accum = cumsum(cnt))

# TODO: dynamics graph over year
country_accum %>%
  filter(year_added == 2015) %>%
  plot_ly(
    type = "choropleth",
    locations = ~country,
    locationmode = "country names",
    z = ~accum,
    color = ~accum,
    colors = "OrRd",
    colorbar = list(title = "Accumlated Sum"),
    text = ~ paste(country, "<br>Accumlated Sum: ", accum)
  )
```

# Gathering data
```{r, warning=FALSE}
type_prop <- by_country_type %>%
  group_by(country) %>%
  mutate(prop = round(cnt / sum(cnt) * 100, 1)) %>%
  group_by(country) %>%
  summarise(total = sum(cnt), prop = prop, type = type) %>%
  as.data.frame() %>%
  top_n(20, wt = total)

custom_order <- type_prop %>%
  arrange(desc(ifelse(type == "Movie", prop, -prop))) %>%
  select(country) %>%
  array() %>%
  flatten() %>%
  unique()
```

```{r}
ggplot(type_prop, aes(y = factor(country, levels = custom_order), x = prop, fill = type)) +
  geom_bar(stat = "identity") +
  geom_text(
    aes(label = scales::percent(prop / 100)),
    position = position_stack(vjust = 0.5),
    color = "white",
    size = 3
  ) +
  labs(
    title = "Proportions of Movie and TV Show by Country",
    y = "Country",
    x = "Proportion (%)",
    fill = "Type"
  ) +
  scale_x_continuous(labels = scales::percent_format(scale = 1), limits = c(0, 100)) +
  scale_fill_manual(values = c("#221f1f", "#b20710")) +
  theme_minimal()
```
