# Prepare
```{r}
library(tidyverse)
library(purrr) # for functional programming
library(wordcloud2) # for creating word cloud
df <- read.csv("data/netflix_titles.csv", na.strings = c("", "NA"))
netflix_color <- colorRampPalette(c('#221f1f', '#b20710', '#e50914'))(10)
```

# Extract the words

```{r}
COMMON_WORDS <- c("a", "in", "at", "be", "of", "the", "an", "to", "on", "he", "she", "and", "his", "with", "her", "for", "their", "when", "this", "from", "as", "is", "by", "after", "that", "who", "but", "into", "up", "they", "him", "out", "must", "are", "about", "it", "its", "while", "one", "them", "where", "has", "more", "over", "have", "off", "two","s")

extract_words <- function(sentences) {
  strsplit(sentences, "\\s+") %>%
    flatten_chr() %>%
    map(str_remove_all, "[^a-zA-Z\\s]") %>%
    map(tolower) %>%
    flatten_chr() %>%
    discard(function(x) x == "") %>% # remove empty string
    discard(function(x) x %in% COMMON_WORDS)
}

word_cloud <- function(data) {
  words <- extract_words(data$description)
  occur <- table(words)
  occur <- sort(occur, decreasing = T)[1:500]
  wordcloud2(occur, color = netflix_color)
}
```

# Plotting

```{r}
word_cloud(df %>% filter(release_year < 2000))
```


```{r}
word_cloud(df %>% filter(2000 <= release_year & release_year < 2010))
```
```{r}
word_cloud(df %>% filter(2010 <= release_year & release_year < 2020))
```
